#!/usr/bin/env bash

set -e

CONFIG="base"
SUFFIX=".conf.yaml"
DOTBOT_DIR="dotbot"

DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

FLATPAK_PLUGIN="dotbot-flathub"

sudo -S -v
while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &

cd "${BASEDIR}"

git config --global url."git@github.com:".insteadOf git://github.com/

git -C "${DOTBOT_DIR}" submodule sync --quiet --recursive
git submodule update --init --recursive "${DOTBOT_DIR}"

source /etc/os-release
case $ID in
    arch)
        echo "Arch"
        . "${BASEDIR}/scripts/linux/${ID}.sh"
        sudo "${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}"  --plugin-dir "${FLATPAK_PLUGIN}" -c "${ID}${SUFFIX}" "${@}"
        ;;
    debian)
        echo "Debian"
        . "${BASEDIR}/scripts/linux/${ID}.sh"
        sudo "${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}"  --plugin-dir "${FLATPAK_PLUGIN}" -c "${ID}${SUFFIX}" "${@}"
        ;;
    fedora)
        echo "Fedora"
        . "${BASEDIR}/scripts/linux/${ID}.sh"
        sudo "${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}"  --plugin-dir "${FLATPAK_PLUGIN}" -c "${ID}${SUFFIX}" "${@}"
        ;;
    *)
        echo "unknown distro ID: $ID, not doing anything special"
        ;;
esac

"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${CONFIG}${SUFFIX}" "${@}"
