#!/usr/bin/env bash

set -e

CONFIG="setup/fedora.conf.yaml"
DOTBOT_DIR="dotbot"

DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

PLUGIN="dotbot-flathub"

sudo -S -v
while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &

cd "${BASEDIR}"

git config --global url."git@github.com:".insteadOf git://github.com/

git -C "${DOTBOT_DIR}" submodule sync --quiet --recursive
git submodule update --init --recursive "${DOTBOT_DIR}"

. "${BASEDIR}/setup/fedora/packages.sh"
. "${BASEDIR}/setup/zsh.sh"

"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" --plugin-dir "${PLUGIN}" -c "${CONFIG}" "${@}"
